version: '3'
services:
  api:
    build: ./build-scripts/rust-watcher
    ports:
      - "8000:8000"
    volumes:
      - ./services/api:/usr/src/app
    env_file:
      - .env

  # web:
  #   image: nginx
  #   volumes:
  #     - ./services/web/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./services/web/webroot:/usr/share/nginx/html
  #   ports:
  #     - "8080:80"

  # web-watcher:
  #  build:
  #    context: ./services/web/
  #    dockerfile: Dockerfile-builder
  #  volumes:
  #    - ./services/web/webroot:/usr/src/app/webroot
  #    - ./services/web/src:/usr/src/app/src

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    volumes:
    - ./data/db:/var/lib/mysql
    - ./db/schema.sql:/docker-entrypoint-initdb.d/initial.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
