version: '3.7'
services:

  db:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'

  web:
    image: node:12.18.4-buster-slim
    ports:
      - 3000:3000
    volumes:
      - ./web:/web:delegated
    command: /bin/sh -c "cd /web; npm install; npm run dev"
    environment:
      - 'DATABASE_URL=postgres://postgres:postgres@db:5432/postgres'
    depends_on:
      - 'db'

  migrator:
    image: flyway/flyway:6.5.7
    command: -n -defaultSchema=public -schemas=public -url=jdbc:postgresql://db:5432/postgres -user=postgres -password=postgres
    environment:
      - 'DATABASE_URL=postgres://postgres:postgres@db:5432/postgres'
    volumes:
      - ./migrator/migrations:/flyway/sql
    depends_on:
      - 'db'

volumes:
  pgdata:
