version: '3.7'
services:

  db:
    image: postgres:12.4
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/mnt/pgdata'

  web:
    image: node:lts-alpine
    ports:
      - 3000:3000
    volumes:
      - ./web:/web:delegated
    command: /bin/sh -c "cd /web; npm install; npm run dev"

volumes:
  pgdata:
